export const CouscousDiscription = "Le couscous est d'une part une semoule de blé dur préparée à l'huile d'olive et d'autre part, une spécialité culinaire issue de la cuisine berbère, à base de couscous, de légumes, d'épices, d'huile d'olive, et de viande ou de poisson";
export const BlanquettedeveauDiscription = "La blanquette de veau ou blanquette de veau à l'ancienne est une recette de cuisine traditionnelle de cuisine française, à base de ragoût de viande de veau marinée, puis mijotée dans un court-bouillon de vin blanc, carotte, poireau, oignon, champignon de Paris, et bouquet garni, liée en sauce blanche à la crème et au beurre.";
export const CôtedebœufDiscription = "La côte de bœuf est un morceau de découpe du bœuf. Elle inclut en une seule portion la partie supérieure d'une côte de l'animal ainsi que la viande qui la couvre.";
export const GigotdagneauDiscription = "Le gigot est la partie du membre postérieur d'un animal comme l'agneau, le chevreuil ou le cerf, qui s'articule entre la hanche et le genou. En boucherie, ces cuisses sont parées pour être vendues généralement en un seul morceau, le plus souvent avec l'os, l'articulation et la souris.";
export const BœufbourguignonDiscription = "Le bœuf bourguignon est une recette de cuisine d'estouffade de bœuf, traditionnelle de la cuisine bourguignonne, cuisinée au vin rouge de Bourgogne, avec une garniture de champignons, de petits oignons et de lardons. Les variations d'accompagnement sont multiples.";
export const RacletteDiscription = "La raclette est une recette de cuisine traditionnelle et emblématique de la cuisine suisse, connue dans le monde entier. Variante des fondues au fromage, elle consiste à faire fondre du raclette et à le racler au fur et à mesure qu’il fond.";
export const TomatesfarciesDiscription = "Les farcis ou petits farcis sont une spécialité culinaire traditionnelle de la cuisine du bassin méditerranéen, exclusivement de la cuisine provençale, cuisine de la Provence méditerranéenne à base de légumes du bassin méditerranéen, et de farce.";
export const MagretdecanardDiscription = "Le magret est un filet de viande maigre, découpé à partir de la poitrine d'une oie ou d'un canard gras, engraissé par gavage, les mêmes qui servent à produire le confit et le foie gras";
export const MoulesfritesDiscription = "Les moules-frites sont un mets très populaire en Belgique et dans le nord de la France, constitué de moules cuites et accompagnées de frites. La portion de moules est généralement d'un kilogramme par personne ; elle est souvent servie à chaque convive dans le récipient de cuisson.";

